// User & Auth
export interface User {
  id: string;
  name: string;
  email: string;
  avatar: string;
  plan: "free" | "creator" | "studio" | "enterprise";
  createdAt: string;
}

// Projects
export interface Project {
  id: string;
  name: string;
  description: string;
  genre: string;
  style: string;
  episodes: number;
  status: "draft" | "in_progress" | "rendering" | "completed";
  thumbnail: string;
  createdAt: string;
  updatedAt: string;
}

// Characters
export interface Character {
  id: string;
  projectId: string;
  name: string;
  role: "protagonist" | "antagonist" | "supporting" | "background";
  description: string;
  appearance: string;
  personality: string;
  voiceType: string;
  emotionProfile: Record<string, number>;
  memoryEntries: number;
  avatar: string;
}

// Episodes
export interface Episode {
  id: string;
  projectId: string;
  number: number;
  title: string;
  brief: string;
  status:
    | "draft"
    | "scripting"
    | "storyboarding"
    | "animating"
    | "voice"
    | "music"
    | "editing"
    | "rendering"
    | "completed";
  duration: string;
  scenes: number;
  progress: number;
  agents: AgentStatus[];
}

// Agent pipeline
export interface AgentStatus {
  name:
    | "Script Writer"
    | "Storyboard"
    | "Animator"
    | "Voice"
    | "Music"
    | "Editor";
  status: "waiting" | "active" | "completed" | "error";
  progress: number;
  startedAt?: string;
  completedAt?: string;
}

// World Atlas
export interface Location {
  id: string;
  projectId: string;
  name: string;
  type: "interior" | "exterior" | "fantasy" | "urban" | "nature";
  description: string;
  mood: string;
  lighting: string;
  timeOfDay: "dawn" | "day" | "dusk" | "night";
  usedInEpisodes: number[];
}

// Soundtrack
export interface Track {
  id: string;
  projectId: string;
  name: string;
  mood: string;
  genre: string;
  duration: string;
  bpm: number;
  status: "generating" | "ready" | "assigned";
  assignedTo?: string;
}

// Render Queue
export interface RenderJob {
  id: string;
  projectId: string;
  episodeId: string;
  episodeName: string;
  resolution: "720p" | "1080p" | "4K";
  status: "queued" | "rendering" | "completed" | "failed";
  progress: number;
  estimatedTime: string;
  gpu: string;
  startedAt?: string;
}

// Workflow
export interface WorkflowNode {
  id: string;
  type: "input" | "agent" | "model" | "output" | "condition";
  name: string;
  x: number;
  y: number;
  config: Record<string, string>;
  connections: string[];
}

// Production Bible
export interface BibleEntry {
  id: string;
  projectId: string;
  category:
    | "character"
    | "location"
    | "lore"
    | "rules"
    | "timeline"
    | "palette";
  title: string;
  content: string;
  updatedAt: string;
  autoGenerated: boolean;
}

// Marketplace
export interface MarketplaceItem {
  id: string;
  name: string;
  creator: string;
  category:
    | "workflow"
    | "template"
    | "preset"
    | "character"
    | "soundtrack";
  price: number;
  rating: number;
  downloads: number;
  description: string;
  tags: string[];
}

// Trend Radar
export interface Trend {
  id: string;
  platform: "tiktok" | "youtube" | "douyin" | "instagram";
  title: string;
  category: string;
  growth: number;
  views: string;
  relevance: number;
  suggestedTemplate?: string;
}

// Notification
export interface Notification {
  id: string;
  type: "success" | "info" | "warning" | "error";
  title: string;
  message: string;
  read: boolean;
  createdAt: string;
}

// Dashboard Stats
export interface DashboardStats {
  totalProjects: number;
  activeRenders: number;
  totalEpisodes: number;
  totalCharacters: number;
  renderHoursUsed: number;
  renderHoursLimit: number;
  storageUsedGB: number;
  storageLimitGB: number;
}
